INSERT INTO airline.flights (
    year,
    quarter,
    month,
    day_of_month,
    day_of_week,
    flight_date,
    marketing_airline_network,
    operated_or_branded_code_share_partners,
    dot_id_marketing_airline,
    iata_code_marketing_airline,
    flight_number_marketing_airline,
    operating_airline,
    dot_id_operating_airline,
    iata_code_operating_airline,
    tail_number,
    flight_number_operating_airline,
    origin_airport_id,
    origin_airport_seq_id,
    origin_city_market_id,
    origin,
    origin_city_name,
    origin_state,
    origin_state_fips,
    origin_state_name,
    origin_wac,
    dest_airport_id,
    dest_airport_seq_id,
    dest_city_market_id,
    dest,
    dest_city_name,
    dest_state,
    dest_state_fips,
    dest_state_name,
    dest_wac,
    crs_dep_time,
    dep_time,
    dep_delay,
    dep_delay_minutes,
    dep_del15,
    departure_delay_groups,
    dep_time_blk,
    taxi_out,
    wheels_off,
    wheels_on,
    taxi_in,
    crs_arr_time,
    arr_time,
    arr_delay,
    arr_delay_minutes,
    arr_del15,
    arrival_delay_groups,
    arr_time_blk,
    cancelled,
    cancellation_code,
    diverted,
    crs_elapsed_time,
    actual_elapsed_time,
    air_time,
    flights,
    distance,
    distance_group,
    carrier_delay,
    weather_delay,
    nas_delay,
    security_delay,
    late_aircraft_delay,
    duplicate_flag
)
SELECT
    NULLIF(year,'')::INTEGER,
    NULLIF(quarter,'')::INTEGER,
    NULLIF(month,'')::INTEGER,
    NULLIF(dayofmonth,'')::INTEGER,
    NULLIF(dayofweek,'')::INTEGER,
    NULLIF(flightdate,'')::DATE,

    marketing_airline_network,
    operated_or_branded_code_share_partners,
    NULLIF(dot_id_marketing_airline,'')::INTEGER,
    iata_code_marketing_airline,
    flight_number_marketing_airline,

    operating_airline,
    NULLIF(dot_id_operating_airline,'')::INTEGER,
    iata_code_operating_airline,
    tail_number,
    flight_number_operating_airline,

    NULLIF(originairportid,'')::INTEGER,
    NULLIF(originairportseqid,'')::INTEGER,
    NULLIF(origincitymarketid,'')::INTEGER,
    origin,
    origincityname,
    originstate,
    originstatefips,
    originstatename,
    NULLIF(originwac,'')::INTEGER,

    NULLIF(destairportid,'')::INTEGER,
    NULLIF(destairportseqid,'')::INTEGER,
    NULLIF(destcitymarketid,'')::INTEGER,
    dest,
    destcityname,
    deststate,
    deststatefips,
    deststatename,
    NULLIF(destwac,'')::INTEGER,

    crsdeptime,
    deptime,
    NULLIF(depdelay,'')::DOUBLE PRECISION,
    NULLIF(depdelayminutes,'')::DOUBLE PRECISION,
    NULLIF(depdel15,'')::DOUBLE PRECISION,
    NULLIF(departuredelaygroups,'')::INTEGER,
    deptimeblk,

    NULLIF(taxiout,'')::DOUBLE PRECISION,
    wheelsoff,
    wheelson,
    NULLIF(taxiin,'')::DOUBLE PRECISION,

    crsarrtime,
    arrtime,
    NULLIF(arrdelay,'')::DOUBLE PRECISION,
    NULLIF(arrdelayminutes,'')::DOUBLE PRECISION,
    NULLIF(arrdel15,'')::DOUBLE PRECISION,
    NULLIF(arrivaldelaygroups,'')::INTEGER,
    arrtimeblk,

    NULLIF(cancelled,'')::DOUBLE PRECISION,
    cancellationcode,
    NULLIF(diverted,'')::DOUBLE PRECISION,

    NULLIF(crselapsedtime,'')::DOUBLE PRECISION,
    NULLIF(actualelapsedtime,'')::DOUBLE PRECISION,
    NULLIF(airtime,'')::DOUBLE PRECISION,
    NULLIF(flights,'')::DOUBLE PRECISION,
    NULLIF(distance,'')::DOUBLE PRECISION,
    NULLIF(distancegroup,'')::INTEGER,

    NULLIF(carrierdelay,'')::DOUBLE PRECISION,
    NULLIF(weatherdelay,'')::DOUBLE PRECISION,
    NULLIF(nasdelay,'')::DOUBLE PRECISION,
    NULLIF(securitydelay,'')::DOUBLE PRECISION,
    NULLIF(lateaircraftdelay,'')::DOUBLE PRECISION,

    duplicate_flag
FROM airline.stage_flights;